- name: Task Variable Playbook
  hosts: localhost
  tasks:
    - name: Print Task Variable
      ansible.builtin.debug:
        vars:
          URL_TASK: www.task.com
      msg: URL_TASK - {{ URL_TASK }}