- name: Task Variable Playbook
  hosts: localhost
  tasks:
    - name: Print task variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
        URL_PLAY: www.facebook.com