- name: Demo on Templates and Copy
  hosts: localhost
  tasks:
    - name: Copying a file
      ansible.builtin.copy:
        src: Copy.conf
        dest: /tmp/Copy.conf

    - name: Copy a file
      ansible.builtin.template:
        src: Copy.conf
        dest: /tmp/Template.conf