- name: Demo on ansible Tags Playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Install Nginx Package
      ansible.builtin.dnf:
        name: nginx
        state: latest
      tags: Nginx

    - name: Install NodeJs Package
      ansible.builtin.dnf:
        name: nodejs
        state: latest
      tags: NodeJs